### ISSUE TITLE
Performance suggestion: Use zstd compression with a dictionary for the logs

### ISSUE THREAD

**Issue by codri** [rubytogether/kirby#10]
Hi,

I've noticed that's you're open for more performance suggestions.
To make this one work you'll have to change the logger that dumps the log files to S3, to compress the logs using zstd and pretrained dictionary.

I can say that it works wonders for repetitive data, which is the case for logs. I got from ~10MB(~50MB uncompressed, with repetitive html files) zip file to ~1MB compressed with a 100KB(if you'll do it, try different dictionary sizes to find the sweet spot) dictionary. All using rust zstd bindings. The sense of wonder never left me since.

Obviously this may not be as good for your case, but I assume it will. Basically you train a dictionary with one of your 1GB logs and use that for compression/decompression in the future, and save the dictionary in S3 as well, associate an archive with the dictionary(maybe by file name: log_dict1_stamp.bin) in case you'll want to train more dictionaries later.

Can't provide any size/perf comparisons since I don't have access to your data. Also these will require more changes to the infrastructure.

Decompression speed should be well over 1GB/s on modern hardware, maybe it's even worth investigating decompressing a stream, and search the data over the stream(but you'll have to copy the found strings), obviously the tool would change a fair amount with this architecture.

Anyway, please feel free to ignore this, if you thought about it before, or it's obvious, or it's not practical.

**Comment by indirect** [comment]
Thanks for writing up this suggestion! That's super interesting. Unfortunately we don't have control over the source of the log files—Fastly drops gzipped files into our S3 bucket directly. We're able to request gzip -9, but that's all we can do.

**Comment by juliana0101** [comment]
S3_zstd_dor.em.mim.faz.sol.a.si)
