### ISSUE TITLE
Create a generic tool to analyse JSON logs

### ISSUE THREAD

**Issue by rubenrua** [rubytogether/kirby#13]
Hi.

Congrats, kirby is really fast. I am used it to analyze Open edX JSON logs.

I am curious about the comparison with MongoDB. If the kirby performance is _similar_ to MongoDB, a generic tool/lib to analyze JSON logs could be very useful. See: https://twitter.com/rubenrua/status/1111240276583071744

I am working in a tool [to import JSON logs into MongoDB](https://github.com/rubenrua/mongo-import-rs/) to compare kirby and MongoDB. I wil update this issue with my results.

**Comment by indirect** [comment]
I'll be interested to see the results! I think MongoDB is probably a bad fit for our particular use case, but I would be interested to hear how long it takes you to process similar volumes of data using it.

**Comment by rubenrua** [comment]
These benchmarks are only an orientation. The purpose is get a fast comparison of the incredible kirby performance and other more generic options. For the benchmarks, two popular generics tool was used: [`MongoDB`](https://www.mongodb.com/) and [`jq`](https://stedolan.github.io/jq/).

# MongoDB.

MongoDB is the more popular document-oriented database. It uses JSON-like documents.

## Scripts
Kirby functionality was divided into two steps: import the data (mongoimport script) and process it with a  MongoDB query (mongo script). The MongoDB query is an aggregation pipeline. It is a simplification of the kirby logic to get closed results. The complexity of the aggregation is less than the complexity of kirby, but the results can be valid to make a fist comparison.

* ./bin/mongoimport:
```
#!/bin/bash
mongoimport --drop -d kirby -c bench "$@"
```

* ./bin/mongo:
```
#!/bin/bash
mongo kirby --eval 'db.bench.aggregate([
{$match: {$or: [
    {request_path: "/api/v1/dependencies", request_query:  ""},
    {request_path: {$in: ["/latest_specs.4.8.gz", "/prerelease_specs.4.8.gz", "/specs.4.8.gz", "/versions"]}}
]}},
{$facet: {
    "tls_cipher": [{$group: {_id: "$tls_cipher" , count: {$sum: 1}}}],
    "versions": [
        {$project: {user_agent: {$split: ["$user_agent", " "]}}},
        {$unwind: "$user_agent"},
        {$group: { _id: { "t" : "$user_agent" }, total_qty : { "$sum" : 1 } }},
        {$sort : { total_qty : -1}}
    ]
}}
])'
```


## Results

```
    Finished release [optimized] target(s) in 0.13s

kirby commit 26a6d92f346dd8014ef3dcf664ef6a9b314fda77
Benchmark #1: target/release/kirby logs/example.log.gz
  Time (mean ± σ):      3.223 s ±  0.012 s    [User: 3.215 s, System: 0.009 s]
  Range (min … max):    3.209 s …  3.243 s    10 runs

Benchmark #2: ./bin/mongoimport logs/example.log
  Time (mean ± σ):     18.899 s ±  0.228 s    [User: 33.654 s, System: 1.014 s]
  Range (min … max):   18.589 s … 19.330 s    10 runs

Benchmark #3: ./bin/mongo
  Time (mean ± σ):      3.090 s ±  0.028 s    [User: 1.649 s, System: 0.030 s]
  Range (min … max):    3.040 s …  3.131 s    10 runs

Summary
  './bin/mongo' ran
    1.04 ± 0.01 times faster than 'target/release/kirby logs/example.log.gz'
    6.12 ± 0.09 times faster than './bin/mongoimport logs/example.log'
```

## Conclusion

MongoDB (import and process) time 21.989 s; (18.899+3.090) and kirby time 3.223 s. **kirby is 6.82 times faster**.

PD: The performance of the MongoDB query could be improved with the use of indexes ([or not](https://jira.mongodb.org/browse/SERVER-29444)).


# JQ

jq is a very good generic tool to process JSONs, but it doesn't support out of the box [gzip compressed files](https://github.com/stedolan/jq/issues/968) and [treating multiple input files](https://github.com/stedolan/jq/issues/744).


## Scripts

The jq command used only analyzes the input, match an invalid condition and it doesn't write any output. It's only an orientation.

```
jq 'select( .request == 1)' logs/example.log > /dev/null
```


## Results


```
Benchmark #1: target/release/kirby logs/example.log.gz
  Time (mean ± σ):      3.231 s ±  0.025 s    [User: 3.223 s, System: 0.009 s]
  Range (min … max):    3.211 s …  3.297 s    10 runs

Benchmark #2: jq 'select( .request == 1)' logs/example.log
  Time (mean ± σ):     14.685 s ±  0.044 s    [User: 14.562 s, System: 0.124 s]
  Range (min … max):   14.648 s … 14.799 s    10 runs

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

Summary
  'target/release/kirby logs/example.log.gz' ran
    4.55 ± 0.04 times faster than 'jq 'select( .request == 1)' logs/example.log'
```


## Conclusion

Despite jq doesn't have any logic, the performance of kirby is **4.5 times faster**.

**Comment by indirect** [comment]
Thanks for your report!
