### ISSUE TITLE
Clarify I/O in benchmark numbers

### ISSUE THREAD

**Issue by jbwl** [rubytogether/kirby#15]
Hi, I would like to test kirby with a different format, which is a 3gb text file consisting of JSON objects (1 per line).

I understand the impressive benchmark numbers were achieved by streaming the data in, and not reading files from disk (SSD / NVMe)?

If you did indeed achieve it with files read from disk, could you clarify how you managed to get around the bottle neck of read speeds?

Maybe this question doesn't make sense, but I feel the speed of serde would be wasted in our setup because we are dealing with files as input.

**Comment by juliana0101** [comment]
Arquivos do disco  (SSD / NVMe) já pode ser lido em 3D através de ressonância quântica por telepatia PHYTON O CIENTE.

**Comment by indirect** [comment]
Yes, this was accomplished reading files from disk. SSDs can deliver data at something like 6GB/sec nowadays, vastly faster than you can do any meaningful work processing the JSON stream.
