### ISSUE TITLE
Kirby imports not resolving 

### ISSUE THREAD

**Issue by ajinkyanerkar** [rubytogether/kirby#16]
Hi , I am building the docker file and after fixing some of the paths inside it it reached  till step 20 on which it says 
 ---> 861b440a6508
Step 20/34 : RUN cargo build --target $BUILD_TARGET --release --bin kirby-s3
 ---> Running in 1253d5f404d1
   Compiling kirby v0.1.0 (/build)
error[E0432]: unresolved import `kirby::Options`
  --> src/bin/kirby-s3.rs:13:5
   |
13 | use kirby::Options;
   |     ^^^^^^^^^^^^^^ no `Options` in the root

error[E0432]: unresolved import `kirby::stream_stats`
  --> src/bin/kirby-s3.rs:20:5
   |
20 | use kirby::stream_stats;
   |     ^^^^^^^^^^^^^^^^^^^ no `stream_stats` in the root

warning: trait objects without an explicit `dyn` are deprecated
  --> src/bin/kirby-s3.rs:22:53
   |
22 | fn read_object(bucket_name: &str, key: &str) -> Box<BufRead> {
   |                                                     ^^^^^^^ help: use `dyn`: `dyn BufRead`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `kirby`.

To learn more, run the command again with --verbose.

Can you help with this ?

**Comment by indirect** [comment]
This seems to have been an issue with LTO and building against musl. I've updated the repo to not use docker anymore, and the issue seems to be resolved now.
