### ISSUE TITLE
Add MIT license?

### ISSUE THREAD

**Issue by xet7** [rubytogether/kirby#2]
Hi,
please add MIT license.

**Comment by indirect** [comment]
Hi,

Why?

**Comment by xet7** [comment]
@indirect 

Because now that this code repository does not have any license, code propietary, it's not Open Source.

Sure if you like that only you can use this code, and keep this propietary, it's your choice. I can not contribute to propietary code.

**Comment by xet7** [comment]
I'm maintainer of Wekan https://wekan.github.io , there I have contributed a lot of code with MIT license. I would like to use your code, but currently it's not possible, because of no license.

**Comment by indirect** [comment]
@xet7 good point. done in 621865e.
