### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by tkaitchuck** [rubytogether/kirby#5]
Looking at your code there are a few areas where it could be made even faster.
* `file.rs` is doing BuffReader::new without specifying a size. This results in a buffer of just 8kb. You might see some improvement by increasing this size.
* In `lib.rs` it's calling lines() on the stream. This is parsing the data from bytes into utf-8 string, which is then handed to serde to deserialize from the utf-8 string. However if you use `split` instead it will give you bytes instead without parsing, which serde is capable of serializing directly. So you can cut out the whole UTF-8 parsing step.
* The counters are going into a hashMap which is using the default ddos resistant hash function, so it's not the fastest. Though you can plug in an alternative hash such as https://crates.io/crates/fnv .
* In the case of the inner map even that is not needed because all the keys are just string constants. It would be both more type safe, and faster to replace the strings with an Enum and use an [enum-map](https://crates.io/crates/enum-map).

**Comment by tkaitchuck** [comment]
Actually, on the second point, there is an even more direct way, Serde can work directly off of the stream:
https://docs.serde.rs/serde_json/struct.StreamDeserializer.html

**Comment by indirect** [comment]
1. Changing the size of the buffer maybe had a small effect, but my tests put it currently within the margin of error.
2. Surprisingly to me, changing from `lines()` to `split()` was also within the margin of error on my tests (something like 200ms in a 3.5s test). I guess the UTF-8 validation must be very, very fast.
3. Looks like this sped things up by about 10%! Thanks for the suggestion.
4. Using `enum-map` sounds nice, but I don't think I have time to implement JSON serialization and deserialization just so I can have one of the three levels be maybe slightly faster. Feel free to send a PR, though. :)

**Comment by tkaitchuck** [comment]
@indirect 
Sorry my fourth point was not clear. What I meant was that here:
https://github.com/rubytogether/kirby/blob/main/src/lib.rs#L109
`counters` is being updated for the keys: 
"tls_cipher", "server_region", "rubygems", "bundler", "ruby", "platform", "ci", and "gemstash"

As far as I can tell, these are the only keys in the map. So it would be good to change these from string constants to an enum. This would make the code more type-safe. But it has the side effect that `counters` can be changed from a hash map to an enum map. (After all there is no point in hashing the same string constant over and over)

**Comment by indirect** [comment]
@tkaitchuck I think I understood what you meant, and tried to do that using `enum-map`, but serde isn't happy with trying to create JSON out of nested enum-maps, which you can see if you try to compile the code in this branch: https://github.com/rubytogether/kirby/compare/enum-map.

My comments about implementing serialization and deserialization were about having to write my own for serde to work with an enum-map.

**Comment by tkaitchuck** [comment]
Ah, for the output. Got it. Makes sense.
