### ISSUE TITLE
Impressive

### ISSUE THREAD

**Issue by mikeptweet** [rubytogether/kirby#8]
That's quite a speedup from the original!

Although this is not a complete solution, I was curious how plain old Javascript would perform. I did a basic test and it performed reasonably well. It processed a one million line log file in 1.5 seconds on my Windows machine (Processor	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)) using the SpiderMonkey JavaScript Engine (https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/)

One can accomplish a lot in a few lines of Javascript code :-)

**C:\spidermonkey>cat sample_1000000.log.txt | js parseJSONFile.js
Processed 1000000 records in 1562ms**

//parseJSONFile.js
var start=Date.now();
var records=[];

function getVal(key,str) {
    return str.split(key+"\/")[1] ? r.split(key+"\/")[1].split(" ")[0] : "";
}    

while(x=JSON.parse(readline())){
    var r=x.user_agent.toLowerCase();
    x._user_Agent={
        "bundler":getVal("bundler",r),
        "rubygems":getVal("rubygems",r),
        "ruby":getVal("ruby",r),
        "platform":r.split("(")[1] ? r.split("(")[1].split(")")[0] : "",
        "command":getVal("command",r),
        "options":getVal("options",r),
        "jruby":getVal("jruby",r),
        "truffleruby":getVal("truffleruby",r),
        "ci":getVal("ci",r),
        "gemstach":getVal("gemstach",r)
    }
    records.push(x);
}
print("Processed "+records.length+" records in "+(Date.now()-start)+"ms");

**Comment by indirect** [comment]
Thanks for the comparison!
